/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author karen
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName());

    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnlimparCFornecedor = new javax.swing.JButton();
        btnCadastrarFornecedor = new javax.swing.JButton();
        btnVoltarTPrincipalFornecedor = new javax.swing.JButton();
        rbFornecedorAtivo = new javax.swing.JRadioButton();
        lblFornecedor = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndFornecedor = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmailFornecedor = new javax.swing.JTextField();
        lblNomeContato = new javax.swing.JLabel();
        txtNomeContato = new javax.swing.JTextField();
        lblDtCadFornecedor = new javax.swing.JLabel();
        txtDtCadFornecedor = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelFornecedor = new javax.swing.JTextField();
        lblObservacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpObsFornecedor = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lblTitulo.setText("Instituto da Beleza");

        btnlimparCFornecedor.setBackground(new java.awt.Color(255, 255, 0));
        btnlimparCFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnlimparCFornecedor.setText("Limpar");
        btnlimparCFornecedor.setToolTipText("Limpa o formulário");
        btnlimparCFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimparCFornecedor.addActionListener(this::btnlimparCFornecedorActionPerformed);

        btnCadastrarFornecedor.setBackground(new java.awt.Color(255, 255, 0));
        btnCadastrarFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarFornecedor.setText("Cadastrar");
        btnCadastrarFornecedor.setToolTipText("Cadastro de Fornecedor");
        btnCadastrarFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrarFornecedor.addActionListener(this::btnCadastrarFornecedorActionPerformed);

        btnVoltarTPrincipalFornecedor.setBackground(new java.awt.Color(255, 255, 0));
        btnVoltarTPrincipalFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltarTPrincipalFornecedor.setText("Voltar");
        btnVoltarTPrincipalFornecedor.setToolTipText("Volta para a tela principal");
        btnVoltarTPrincipalFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltarTPrincipalFornecedor.addActionListener(this::btnVoltarTPrincipalFornecedorActionPerformed);

        rbFornecedorAtivo.setText("Fornecedor Ativo");
        rbFornecedorAtivo.setToolTipText("Marque quando o cliente for assíduo");

        lblFornecedor.setText("Empresa:");

        txtFornecedor.setToolTipText("Escreva o nome completo");

        lblCnpj.setText("CNPJ:");

        txtCnpj.setToolTipText("Escreva o CPF");

        lblEndereco.setText("Endereço:");

        txtEndFornecedor.setToolTipText("Endereço completo");

        lblEmail.setText("E-mail");

        txtEmailFornecedor.setToolTipText("Email não obrigatório");

        lblNomeContato.setText("Contato:");

        txtNomeContato.setToolTipText("Data válida com ano XXXX");

        lblDtCadFornecedor.setText("Data de Cadastro:");

        txtDtCadFornecedor.setToolTipText("Data de hoje, ano XXXX");

        lblTelefone.setText("Telefone:");

        txtTelFornecedor.setToolTipText("Telefone ou celular com DDD");

        lblObservacoes.setText("Observações:");

        txpObsFornecedor.setForeground(new java.awt.Color(153, 153, 153));
        txpObsFornecedor.setText("Prazos de entregas, produto mais comprado");
        txpObsFornecedor.setToolTipText("Observações sobre produtos e entregas");
        jScrollPane1.setViewportView(txpObsFornecedor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFornecedor)
                            .addComponent(lblCnpj))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCnpj)
                            .addComponent(txtFornecedor))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rbFornecedorAtivo))
                            .addComponent(lblTitulo))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblObservacoes)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addGap(18, 18, 18)
                                .addComponent(txtEndFornecedor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblEmail)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEmailFornecedor))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNomeContato)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(lblDtCadFornecedor)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDtCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTelefone)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnCadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 65, Short.MAX_VALUE)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVoltarTPrincipalFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(btnlimparCFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbFornecedorAtivo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFornecedor)
                            .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCnpj)
                            .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeContato)
                    .addComponent(txtNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtCadFornecedor)
                    .addComponent(txtDtCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlimparCFornecedor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblObservacoes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarTPrincipalFornecedor)
                    .addComponent(btnCadastrarFornecedor))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFornecedorActionPerformed
        JOptionPane.showMessageDialog(null, "Cadastro Feito com Sucesso");
         txtFornecedor.setText("");
        txtCnpj.setText("");
        txtEndFornecedor.setText("");
        txtEmailFornecedor.setText("");
        txtNomeContato.setText("");
        txtDtCadFornecedor.setText("");
        txtTelFornecedor.setText("");
        txtFornecedor.requestFocusInWindow();
    }//GEN-LAST:event_btnCadastrarFornecedorActionPerformed

    private void btnVoltarTPrincipalFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTPrincipalFornecedorActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarTPrincipalFornecedorActionPerformed

    private void btnlimparCFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparCFornecedorActionPerformed
        txtFornecedor.setText("");
        txtCnpj.setText("");
        txtEndFornecedor.setText("");
        txtEmailFornecedor.setText("");
        txtNomeContato.setText("");
        txtDtCadFornecedor.setText("");
        txtTelFornecedor.setText("");
        txtFornecedor.requestFocusInWindow();
    }//GEN-LAST:event_btnlimparCFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroFornecedor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFornecedor;
    private javax.swing.JButton btnVoltarTPrincipalFornecedor;
    private javax.swing.JButton btnlimparCFornecedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblDtCadFornecedor;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblNomeContato;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbFornecedorAtivo;
    private javax.swing.JTextPane txpObsFornecedor;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtDtCadFornecedor;
    private javax.swing.JTextField txtEmailFornecedor;
    private javax.swing.JTextField txtEndFornecedor;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtNomeContato;
    private javax.swing.JTextField txtTelFornecedor;
    // End of variables declaration//GEN-END:variables
}
